BASEDICT = \
         { 'T': 'U', 'FHU': 'U', '2PR': 'G', 'CPN': 'C', 'MA6': 'A', 'MIA': 'A',
           'SRA': 'A', 'AP7': 'A', 'PSU': 'U', 'G25': 'G', 'C31': 'C',
           'CCC': 'C', '12A': 'A', 'S4C': 'C', 'UAR': 'U', 'TAF': 'U',
           'UR3': 'U', 'C2L': 'C', 'RIA': 'A', 'OMC': 'C', 'GPN': 'G',
           'GS': 'G', 'PPU': 'A', 'TPN': 'U', 'BGM': 'G', 'PR5': 'A',
           'LHU': 'U', '6MZ': 'A', 'MRG': 'G', 'PHA': 'A', 'APN': 'A',
           'MAD': 'A', 'UBB': 'U', 'PYO': 'U', 'M5M': 'C', '4OC': 'C',
           'G2L': 'G', 'AET': 'A', 'LKC': 'C', 'CB2': 'C', 'U36': 'U',
           'U34': 'U', 'U33': 'U', 'T3P': 'U', 'U31': 'U', '1MA': 'A',
           '1MG': 'G', 'PU': 'A', 'G7M': 'G', '10C': 'C', 'U2N': 'U',
           'MNU': 'U', 'TCP': 'U', 'M2G': 'G', '7MG': 'G', 'CSL': 'C',
           'G': 'G', 'C43': 'C', 'P1P': 'C', 'A44': 'A', '5FU': 'U',
           '5MU': 'U', 'SSU': 'U', '6HT': 'U', 'A5M': 'C', 'CBR': 'C',
           'LCG': 'G', 'CBV': 'C', 'LCC': 'C', '5MC': 'C', 'LCA': 'A', 
           '6HG': 'G', '6HA': 'A', 'ANZ': 'A', 'CM0': 'U', 'U8U': 'U',
           'UMS': 'U', 'ATL': 'U', '5CG': 'G', 'XUG': 'G', 'SUR': 'U',
           'A2L': 'A', 'A2M': 'A', 'UD5': 'U', '1SC': 'C', 'CH': 'C',
           'PDU': 'U', 'FMU': 'U', 'TFO': 'A', 'GTP': 'G', 'TLB': 'U',
           '3DA': 'A', 'TLN': 'U', 'GDP': 'G', 'TM2': 'U', 'A23': 'A',
           'OMG': 'G', 'H2U': 'U', 'MMT': 'U', 'BRU': 'U', 'YYG': 'G',
           'N5M': 'C', 'OMU': 'U', '70U': 'U', 'SC': 'C', '4SU': 'U', 
           'QUO': 'G', 'GNG': 'G', '5IC': 'C', '2MU': 'U', 'CAR': 'C',
           'YG': 'G', 'G48': 'G', '2MA': 'A', '2MG': 'G', '5AA': 'A',
           'DU': 'U', 'T6A': 'A', 'LG': 'G', 'LC': 'C', 'TT': 'U',
           '5PC': 'C', 'ONE': 'U', 'GAO': 'G', 'TSP': 'U', 'PGP': 'G',
           'UCL': 'U', 'A': 'A', '5BU': 'U', 'IU': 'U', 'MTU': 'A',
           'AS': 'A', 'IC': 'C', 'P5P': 'A', 'IG': 'G', 'N6G': 'G',
           'CFL': 'C', 'U2L': 'U', '6HC': 'C', 'GFL': 'G', 'AVC': 'A', 
           'U5P': 'U', 'C5P': 'C', 'GUA': 'G', 'CYT': 'C', 'ADE': 'A',
           'URI': 'U', '6IA': 'A', 'PQ1': 'G', 'U': 'U', 'C': 'C',
           'CFL': 'C', 'UFT': 'U', 'G46': 'G', 'I': 'A', 'DT': 'U',
           'DC': 'C', 'DG': 'G', 'DA': 'A'}
